### ISSUE TITLE
Detail improvements

### ISSUE THREAD

**Issue by FrzMtrsprt** [CharlieEtienne/material-github#39]
Hi! First of all, thanks for bringing Material Design to Github!

**Folder icons**
![image](https://user-images.githubusercontent.com/15852717/86871042-1687fa80-c10c-11ea-909a-5f466dd6ebdc.png)
I noticed that the folder icons doesn't seem to follow the selected accent color. Is it a bug, or is it simply not included in the theme? It would be really nice if you could theme these icons!

**Tags' font size**
![image](https://user-images.githubusercontent.com/15852717/86871104-38817d00-c10c-11ea-9a02-dad06a5f7bc7.png)
In my case, the text in the tag is not aligned to center, and has a 12 px font size. The same problem also occurs on repository tags. I am using Chrome 83 with Stylus 1.5.11.

**Comment by CharlieEtienne** [comment]
Hi @FrzMtrsprt,

Folder icons color is fixed in https://github.com/CharlieEtienne/material-github/commit/62ab84a0658e10ddc0432c55b3f5b974ae486d0a 

About the tags text not being vertically centered, it seems the problem appears without theme active. This comes from github so you could open an issue or PR in GitHub official repo.

I'm going to close this issue but feel free to reopen it if I'm mistaking.

Cheers,

Charlie

**Comment by FrzMtrsprt** [comment]
Hi @CharlieEtienne!
I noticed that the folder colors are not working again, it appears that Github has changed the folder color from `color-blue-3` to `color-files-explorer-icon`. Hope this will be fixed, thx!

**Comment by CharlieEtienne** [comment]
Hi @FrzMtrsprt , actually it has been fixed in d06936d55ed7516afb046c0b0d284b5f306f67e5, so you can update and it should work!

**Comment by FrzMtrsprt** [comment]
Now it works, thx!
